baseURL = 'https://blog.akvicor.com/'
languageCode = 'zh-cn'
title = "Akvicor's Blog"

# å¯ç”¨ä¸»é¢˜
theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 11
enableGitInfo = true

[params]
    author = 'Akvicor'
    slogan = 'å¤ªæ£’äº†ï¼Œæˆ‘é€æ¸ç†è§£ä¸€åˆ‡'

    en = false
    # è‹±æ–‡é¦–é¡µæ ‡é¢˜
    homeTitleEn = "Akvicor's Blog"
    # ä¸­æ–‡é¦–é¡µæ ‡é¢˜
    homeTitleZh = "Akvicorçš„åšå®¢"

    # æ¿€æ´»æš—è‰²æ¨¡å¼ï¼Œ
    # ç”±äºé™æ€é¡µé¢çš„é™åˆ¶ï¼Œæˆ‘ä»¬ä½¿ç”¨æµè§ˆå™¨æœ¬åœ°å­˜å‚¨æ¥è®°å¿†è¯¥çŠ¶æ€ï¼Œ
    # å¦‚æœè®¾ç½®ä¸º `true` åï¼Œé»˜è®¤ä¸æ˜¯æš—è‰²æ¨¡å¼ï¼Œæ¸…é™¤æµè§ˆå™¨ç¼“å­˜ååˆ·æ–°é¡µé¢å³å¯
    dark = false

    # æ–‡ç« åˆ—è¡¨é¡µå•åˆ—æ˜¾ç¤º
    isSingleColumnOfPostList = true

    # æ˜¯å¦æ˜¾ç¤ºç›¸é‚»é¡µé“¾æ¥
    isShowPrevNextLink = true

    # æ¿€æ´»é¡µé¢åŠ è½½æ—¶çš„è¿‡æ¸¡åŠ¨ç”»
    hasActiveAnimate = true

    # æ¿€æ´» cool æ¨¡å¼ï¼Œé…·çˆ½ä½†æ˜¯æ¶ˆè€—èµ„æºä¹Ÿæ›´å¤šï¼Œ
    # å¦‚æœæƒ³æ›´æ¢é¡µé¢èƒŒæ™¯ï¼Œåªéœ€è¦å°†å›¾ç‰‡å‘½åä¸º `default.jpg` åï¼Œç½®äº `/static/imgs/bg` æ–‡ä»¶å¤¹ä¸­å³å¯ï¼Œ
    # æµè§ˆå™¨æœ‰ç¼“å­˜ï¼Œæ›´æ¢åå¼ºåˆ¶é¡µé¢åˆ·æ–°ï¼ˆå¿«æ·é”®ä¸º Ctrl+Shift+Rï¼‰ä¸€ä¸‹å³å¯
    hasActiveCool = false

    # å±•å¼€/æŠ˜å ä»£ç å—ï¼Œé»˜è®¤ä¸æŠ˜å ï¼Œ
    # è®¾ç½®ä¸º `true` ï¼Œåˆ™é»˜è®¤æŠ˜å æ‰€æœ‰ä»£ç å—ï¼Œ
    # æç¤ºï¼Œåœ¨ç§»åŠ¨è®¾å¤‡ä¸­ï¼Œç³»ç»Ÿè®¾ç½®ä¸ºæ°¸ä¹…æŠ˜å ä»£ç å—
    # (è¯¥é¡¹è®¾ç½®ä¸é‡è¦ï¼Œå®Œå…¨æ˜¯ä¸ªäººå–œå¥½)
    hasFoldAllCodeBlocks = false

    # åŠ¨æ€æ ‡é¢˜
    funnyTitle = false

    # consoleç‰¹æ®Šå­—ç¬¦
	consoleLogAkvicor = true
	consoleLogWoW = true

	# æ•°å­¦å…¬å¼æ”¯æŒ
	viryLatex = false # ä½¿ç”¨è‡ªå»ºlatexæ¸²æŸ“æœåŠ¡
    mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

    # å¦‚ä¸‹å¯¼èˆªé“¾æ¥ï¼Œä½ åº”è¯¥åˆ›å»ºå¯¹åº”çš„ `.md` æ–‡ä»¶ï¼Œä»¥ç”Ÿæˆå¯¹åº”çš„é¡µé¢
    # -----------------------------------
    # Nav - nav.md or nav/index.md
    # Search - search.md or search/index.md
    # Archive - archive.md or archive/index.md
    # Wiki - posts/wiki.md or wiki/index.md
    # About - about.md or about/index.md
    # -----------------------------------
    # èœå•é€‰é¡¹å®šåˆ¶ï¼Œä½¿ç”¨ `00ã€01ã€23` ç­‰è¿›è¡Œé€‰é¡¹é¡ºåºè°ƒæ•´
    # ğŸ¶ğŸ‰ğŸ‘€ğŸ’¡ğŸ‘“ğŸŒ
    [params.menu]
        [params.menu.00]
            active = true
            path = '/posts'
            en = 'Posts'
            zh = 'æ–‡ç« '
            icon = 'ğŸ“œ'
        [params.menu.11]
            active = true
            path = '/search'
            en = 'Search'
            zh = 'æœç´¢'
            icon = 'ğŸ”'
        [params.menu.22]
            active = true
            path = '/archive'
            en = 'Archive'
            zh = 'å½’æ¡£'
            icon = 'ğŸ‰'
        [params.menu.33]
            active = true
            path = '/nav'
            en = 'Nav'
            zh = 'å¯¼èˆª'
            icon = 'ğŸ¯'
        [params.menu.44]
            active = true
            path = '/about'
            en = 'About'
            zh = 'å…³äº'
            icon = 'ğŸŒ'

    # é¦–é¡µå›¾ç‰‡/æ–‡å­—
    [params.img]
        # å¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºå›¾ç‰‡ï¼Œæƒ³æ˜¾ç¤ºä¸€æ®µè¯ï¼Œåªéœ€è¦
        # è®¾ç½® `noImgButWords` ä¸º true å³å¯
        notImgButWords = false
        # å†…ç½®äº† `girl.png, wukong.jpg, and tux.jpg, cat.svg â€¦â€¦`ï¼Œå½“ç„¶ä½ å¯ä»¥
        # æŠŠè‡ªå·±å–œæ¬¢å›¾ç‰‡æ”¾åœ¨ `static/imgs/` ç›®å½•ä¸­ï¼Œå¹¶åœ¨ `src` å¼•ç”¨å®ƒ,
        # ä½ è¿˜å¯ä»¥é€šè¿‡ `width` è°ƒæ•´å¼•å…¥å›¾ç‰‡çš„æ˜¾ç¤ºå¤§å°ï¼Œ
        # å¦‚æœï¼Œå°† `width` è®¾ç½®ä¸º '' æˆ– 0 ï¼Œ
        # å°†é»˜è®¤ä½¿ç”¨å›¾ç‰‡è‡ªèº«åˆ†è¾¨ç‡å°ºå¯¸
        src = 'girl.png'
        width = 0
        words = "â€œå¾ªæ­¤è‹¦æ—…ï¼Œä»¥è¾¾æ˜Ÿè¾°â€"

    [params.contact]
        ## å¤‡æ¡ˆå·ï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
        # icp = ''
        ## å¤‡æ¡ˆé“¾æ¥
        # icplink = '//beian.miit.gov.cn'
        ## e.g. https://weibo.com/u/6867589681
        # weibo = '6867589681'
        ## å¾®ä¿¡äºŒç»´ç åœ°å€
        # wechat = 'imgs/bg/wechat.jpg'
        ## e.g. https://www.zhihu.com/people/Akvicor
        # zhihu = 'Akvicor'
        ## e.g. https://www.jianshu.com/u/eebcc2974936
        # jianshu = 'eebcc2974936'
        email = 'akvicor@akvicor.com'
        ## e.g. https://github.com/AkvicorEdwards
        github = 'AkvicorEdwards'
        ## e.g. https://space.bilibili.com/12194502
        bilibili = '12194502'
        ## e.g. https://twitter.com/Akvicor
        # twitter = 'Akvicor'
        ## e.g. https://facebook.com/Akvicor
        # facebook = 'Akvicor'
        ## e.g. https://www.instagram.com/Akvicor
        # instagram = 'Akvicor'
        ## e.g. https://www.youtube.com/channel/UCkWIBwe3rZTDAmBs0GJngkA
        # youtube = 'UCkWIBwe3rZTDAmBs0GJngkA'
        ## e.g. https://web.telegram.org/k/#@Akvicor
        # telegram = 'Akvicor'
        ## å›¾æ ‡é¢œè‰²ï¼Œé»˜è®¤ä¸ºæµ…ç°è‰²
        color = '#696969'
        ## è”ç³»æ ‡è¯­ï¼Œä¸æƒ³æ˜¾ç¤ºï¼Œå¯ä»¥ç½®ç©º 'Find me via : )'
        slogan = ''

    # åœ¨å¼€å‘ç¯å¢ƒä¸‹ï¼ˆhttp://localhost:1313/ï¼‰ï¼Œä¸å†å¯ç”¨è¯„è®ºæ’ä»¶ï¼Œ
    # å¦‚æœæƒ³åœ¨å¼€å‘ç¯å¢ƒä¸‹å¯ç”¨å®ƒï¼Œä¿®æ”¹æœåŠ¡ç«¯å£å³å¯ï¼Œå¦‚ä¸‹
    # hugo server -p=1314
    [params.utterances]
        # æ˜¯å¦å¯ç”¨è¯„è®ºæ’ä»¶
        active = false
        # è¾“å…¥ä½ çš„ä»“åº“åç§°
        repo = "AkvicorEdwards/blog"
        issueTerm = "pathname"
        theme = "github-light"
        crossorigin = "anonymous"

# ä»¥ä¸‹ä¸º Markdown è§£ææ“çš„ä¸€äº›è®¾ç½®ï¼Œ
# å»ºè®®ä¿æŒä¸å˜
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        # ä»£ç å—æ˜¾ç¤ºé£æ ¼ã€è¡Œå·æ˜¾ç¤º
        style = "github"
        lineNos = false
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
